simplesaga:
  jwt:
    secret: secret
server:
  port: 8080
spring:
  application.name: simple-order-saga-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simple_order_saga
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: db/changeLog/db.changelog-master.xml
    drop-first: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: SIMPLE_ORDER_SAGA_USER
      auto-offset-reset: latest
