version: '3'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.96.0/20
          gateway: 192.168.96.1
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: 'simple-order-saga-zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: 'simple-order-saga-kafka'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "TOPIC:1:1"
  postgres:
    image: postgres:15
    container_name: 'simple-order-saga-postgres'
    environment:
      POSTGRES_DB: "simple-order-saga"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PG_DATA: /var/lib/postgresql/data/db-files
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
